import type { AutoBackupConfig } from '../config/types.js';
import * as path from 'node:path/posix';

function shellQuote(s: string): string {
  if (/^[A-Za-z0-9_./@:%+=,-]+$/.test(s)) {
    return s;
  }
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Build the shell command that backs up an existing remote file before
 * an SFTP write replaces it. Returns null when no backup should run
 * (autoBackup disabled, or 'upload' isn't in the commands list, or the
 * target is under the backup dir itself).
 *
 * The returned command is conditional: if dest doesn't exist on the
 * remote, the backup silently no-ops; if dest exists, it runs
 * `mkdir -p backupDir && cp -a dest backupDir/<ts>_<basename>`. Run via
 * runRemoteCommand and treat non-zero exit as a fatal error — that
 * matches `wrapBackup`'s "abort on backup failure" rule for shell
 * commands. Returns null → caller proceeds straight to write.
 */
export function buildSftpBackupCommand(
  destPath: string,
  cfg: AutoBackupConfig
): string | null {
  if (!cfg.enabled || !cfg.commands.includes('upload')) {
    return null;
  }
  const backupDir = cfg.backupDir.replace(/\/+$/, '');
  // Skip if dest IS the backup dir or under it — would loop on itself.
  const cleanDest = destPath.replace(/\/+$/, '');
  if (cleanDest === backupDir || cleanDest.startsWith(backupDir + '/')) {
    return null;
  }
  const baseName = path.basename(destPath);
  const dirQ = shellQuote(backupDir);
  const destQ = shellQuote(destPath);
  const baseQ = shellQuote(baseName);
  // Timestamp is generated by the *remote* shell so backups reflect the
  // server's clock at the moment of backup (forensically more useful than
  // the operator's machine's clock if the two have drifted). Format
  // matches `wrapBackup` and JS `toISOString().replace(/[:.]/g,'-')`:
  // YYYY-MM-DDTHH-MM-SS-mmmZ. `%3N` is a GNU coreutils extension —
  // BusyBox/macOS sshd would emit a literal `%3N`, visible but non-fatal.
  // The $(...) cannot be inside single quotes or the shell sees it as
  // a literal, so we splice it bare between the quoted pieces.
  const backupExpr = `${dirQ}/$(date -u +%Y-%m-%dT%H-%M-%S-%3NZ)_${baseQ}`;
  return `if [ -e ${destQ} ]; then mkdir -p ${dirQ} && cp -a ${destQ} ${backupExpr}; fi`;
}

function hasGlob(target: string): boolean {
  return /[*?[]/.test(target);
}

/**
 * Wrap a destructive command with a best-effort backup.
 *
 * - rm/mv/cp/sed/redirect-overwrite get a `cp -a $TARGET $BACKUP_DIR/<ts>_<name>` prefix
 * - on backup failure the original command is aborted (else-branch returns non-zero)
 * - wildcard targets are skipped with a warning
 */
export function wrapBackup(command: string, cfg: AutoBackupConfig): string {
  if (!cfg.enabled || !command.trim()) {
    return command;
  }

  const stripped = command.trim();
  const cdMatch = stripped.match(/^(cd\s+\S+\s*&&\s*)/);
  const cdPrefix = cdMatch ? cdMatch[1] : '';
  const workCmd = cdMatch ? stripped.slice(cdPrefix.length) : stripped;

  let work = workCmd.trim();
  let hasSudo = false;
  if (work.startsWith('sudo ')) {
    hasSudo = true;
    work = work.slice(5).trim();
  }

  const parts = work.split(/\s+/);
  if (parts.length === 0 || !parts[0]) {
    return command;
  }
  const baseCmd = parts[0];
  const sudoPrefix = hasSudo ? 'sudo ' : '';
  const backupDir = cfg.backupDir.replace(/\/+$/, '');
  const backupDirQ = shellQuote(backupDir);

  // Redirect overwrite: cmd > /path/file (skip 2>, &>, etc.)
  if (cfg.commands.includes('>')) {
    // Match a `>` that is *neither* `>>` (append) nor `2>` / `&>` (fd redirect).
    // The negative lookbehind excludes digits, `&`, and `>` itself; the
    // negative lookahead excludes a following `>`.
    const m = workCmd.match(/(?<![0-9&>])>(?!>)\s*(\S+)/);
    if (m && m[1]) {
      const target = m[1];
      if (target !== '/dev/null') {
        if (hasGlob(target)) {
          return `echo ${shellQuote(`[WARN] auto-backup skipped — wildcard target: ${target}`)}; ${command}`;
        }
        const cleanTarget = target.replace(/\/+$/, '');
        if (cleanTarget === backupDir || cleanTarget.startsWith(backupDir + '/')) {
          return command;
        }
        const basename = cleanTarget.split('/').pop() ?? cleanTarget;
        const bak = `${backupDirQ}/$(date -u +%Y-%m-%dT%H-%M-%S-%3NZ)_${basename}`;
        const targetQ = shellQuote(target);
        return (
          `${cdPrefix}` +
          `if ${sudoPrefix}mkdir -p ${backupDirQ} && ${sudoPrefix}cp -a ${targetQ} ${bak} && echo ${shellQuote(`[backup] ${target} -> ${backupDir}`)}; then ` +
          `${workCmd}; ` +
          `else echo '[WARN] backup failed — command aborted'; exit 1; fi`
        );
      }
    }
  }

  if (!cfg.commands.includes(baseCmd)) {
    return command;
  }

  const targets: string[] = [];
  if (baseCmd === 'rm') {
    for (const p of parts.slice(1)) {
      if (!p.startsWith('-')) {
        targets.push(p);
      }
    }
  } else if (baseCmd === 'mv') {
    for (const p of parts.slice(1)) {
      if (!p.startsWith('-')) {
        targets.push(p);
        break;
      }
    }
  } else if (baseCmd === 'cp') {
    const nonFlag = parts.slice(1).filter(p => !p.startsWith('-'));
    if (nonFlag.length >= 2) {
      const last = nonFlag[nonFlag.length - 1];
      if (last) {
        targets.push(last);
      }
    }
  } else if (baseCmd === 'sed') {
    const hasInPlace = parts.slice(1).some(p => p === '-i' || p.startsWith('-i'));
    if (!hasInPlace) {
      return command;
    }
    let skipExpr = true;
    for (const p of parts.slice(1)) {
      if (p.startsWith('-')) {
        continue;
      }
      if (skipExpr) {
        skipExpr = false;
        continue;
      }
      targets.push(p);
    }
  } else {
    return command;
  }

  if (targets.length === 0) {
    return command;
  }

  const backupTargets: string[] = [];
  let sawGlob = false;
  for (const t of targets) {
    if (hasGlob(t)) {
      sawGlob = true;
      continue;
    }
    const clean = t.replace(/\/+$/, '');
    if (clean === backupDir || clean.startsWith(backupDir + '/')) {
      continue;
    }
    backupTargets.push(t);
  }

  if (backupTargets.length === 0) {
    if (sawGlob) {
      const first = targets.find(hasGlob) ?? '';
      return `echo ${shellQuote(`[WARN] auto-backup skipped — wildcard target: ${first}`)}; ${command}`;
    }
    return command;
  }

  const backupCmds = backupTargets.map(t => {
    const clean = t.replace(/\/+$/, '');
    const basename = clean.split('/').pop() ?? clean;
    const bak = `${backupDirQ}/$(date -u +%Y-%m-%dT%H-%M-%S-%3NZ)_${basename}`;
    return `${sudoPrefix}cp -a ${shellQuote(t)} ${bak} && echo ${shellQuote(`[backup] ${t} -> ${backupDir}`)}`;
  });

  const globWarn = sawGlob ? `echo '[WARN] auto-backup skipped for wildcard targets'; ` : '';

  return (
    `${cdPrefix}` +
    `if ${sudoPrefix}mkdir -p ${backupDirQ} && ${backupCmds.join(' && ')}; then ` +
    `${globWarn}${workCmd}; ` +
    `else echo '[WARN] backup failed — command aborted'; exit 1; fi`
  );
}
