import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as vscode from 'vscode';
import type { AppConfig, TaskConfig } from '../config/types.js';
import type { SelectionState } from '../state/selection.js';
import type { Workspace } from '../workspace.js';
import type { PrefsStore } from '../state/prefs.js';
import type { ConfigStore } from '../config/loader.js';
import { reorderTasksWithinSource, taskIdentity, type DropPlacement, type TaskIdentity } from '../commands/taskOrder.js';

/** Names auto-generated by `compat.ts:autoTaskName` follow `<type>-<N>`. We
 *  don't show those in the tree because they carry zero info — the command
 *  itself is more useful as the row label. Real user-given names always
 *  win: `uptime`, `disk-usage`, etc. */
const AUTO_NAME_RE = /^(command|upload|script)-\d+$/;

class TaskNode extends vscode.TreeItem {
  readonly kind = 'task' as const;
  /** Absolute path to the YAML file this task came from. Stored as a plain
   *  field rather than `resourceUri` so VSCode's file-decoration system
   *  doesn't apply gitignored-fade / git-status colors to the row — the
   *  tasks should read as primary content, not a file listing. */
  readonly sourcePath: string | undefined;
  constructor(readonly task: TaskConfig, selected: boolean, sourcePath?: string) {
    const summary = task.type === 'command'
      ? task.command ?? ''
      : task.type === 'upload'
        ? `${task.src} → ${task.dest}`
        : `${task.src}${task.args ? ' ' + task.args : ''}`;
    const isAutoName = AUTO_NAME_RE.test(task.name);
    // Auto-named row: the command IS the label; description stays empty
    // so the row reads as a single command. Real-named row: name is the
    // label, command body is the secondary description.
    const label = isAutoName ? summary : task.name;
    super(label || task.name, vscode.TreeItemCollapsibleState.None);
    this.description = isAutoName ? '' : summary;
    this.tooltip = new vscode.MarkdownString(
      (isAutoName ? '' : `**${task.name}** · `) + `${task.type}\n\n` +
      (summary ? `\`${summary}\`\n\n` : '') +
      `timeout: ${task.timeout}s` +
      (task.confirmBeforeRun ? ' · confirm before run' : '')
    );
    this.iconPath = iconForType(task.type);
    this.contextValue = `task-${task.type}`;
    if (sourcePath && sourcePath !== '(unknown)') {
      this.sourcePath = sourcePath;
    }
    this.checkboxState = selected
      ? vscode.TreeItemCheckboxState.Checked
      : vscode.TreeItemCheckboxState.Unchecked;
  }
}

/**
 * Expandable "Task Files" header row at the top of the Tasks tree. Mirrors
 * the Env / Module filter pattern in the Servers tree — children are
 * checkbox rows for each `*.yml` in `<workspace>/tasks/`.
 */
class TaskFileGroupNode extends vscode.TreeItem {
  readonly kind = 'task-file-group' as const;
  constructor(activeCount: number, totalCount: number) {
    super('Task Files', vscode.TreeItemCollapsibleState.Collapsed);
    this.description = totalCount === 0
      ? '(none in tasks/)'
      : activeCount === 0
        ? '(none active)'
        : `${activeCount} of ${totalCount} active`;
    this.iconPath = new vscode.ThemeIcon('files');
    this.contextValue = 'task-file-group';
  }
}

class TaskFileNode extends vscode.TreeItem {
  readonly kind = 'task-file' as const;
  /** Absolute path to the YAML file. Plain field instead of `resourceUri`
   *  to avoid the gitignored-fade decoration on rows pointing into
   *  `dev-workspace/` or other gitignored task dirs. */
  readonly sourcePath: string | undefined;
  constructor(
    readonly fileName: string,
    selected: boolean,
    opts: { isActiveConfig?: boolean; fullPath?: string } = {}
  ) {
    super(fileName, vscode.TreeItemCollapsibleState.None);
    this.contextValue = opts.isActiveConfig ? 'task-file-active-config' : 'task-file';
    if (opts.isActiveConfig) {
      // Active config row gets a distinct icon + label so the user knows it
      // isn't a `tasks/*.yml` file but the live config itself.
      this.description = '(active config)';
      this.iconPath = new vscode.ThemeIcon('settings');
    }
    if (opts.fullPath) {
      this.sourcePath = opts.fullPath;
    }
    this.checkboxState = selected
      ? vscode.TreeItemCheckboxState.Checked
      : vscode.TreeItemCheckboxState.Unchecked;
  }
}

/**
 * One-line preference row at the bottom of the Tasks tree exposing the
 * deselect-after-run setting via a *real* TreeItem checkbox — the
 * only widget VSCode renders with a clear ticked / unticked state in
 * extension UI. View-title menus can show `$(check)` codicons in some
 * surfaces but not consistently in the overflow `…` menu.
 */
class PrefToggleNode extends vscode.TreeItem {
  readonly kind = 'pref-toggle' as const;
  constructor(readonly prefId: 'deselectAfterRun', label: string, value: boolean) {
    super(label, vscode.TreeItemCollapsibleState.None);
    this.contextValue = `pref-${prefId}`;
    this.iconPath = new vscode.ThemeIcon('settings-gear');
    this.checkboxState = value
      ? vscode.TreeItemCheckboxState.Checked
      : vscode.TreeItemCheckboxState.Unchecked;
    this.tooltip = value
      ? 'Currently ON — uncheck to leave tasks ticked after run'
      : 'Currently OFF — check to auto-untick tasks after running them';
  }
}

/**
 * Top-level group node for tasks coming from a single source file. Lets
 * the operator see which file every task originates from at a glance —
 * useful when several task files are active and the same name might be
 * overridden across them.
 */
class TaskSourceGroupNode extends vscode.TreeItem {
  readonly kind = 'task-source' as const;
  constructor(readonly sourceLabel: string, readonly sourcePath: string, readonly count: number) {
    super(`${sourceLabel} (${count})`, vscode.TreeItemCollapsibleState.Expanded);
    this.iconPath = new vscode.ThemeIcon('file-code');
    this.contextValue = 'task-source';
    this.tooltip = sourcePath;
    // No `resourceUri` here on purpose — VSCode's gitignored decorator
    // would fade the row when sourcePath lives under a gitignored
    // directory (typical for tasks/ in a dev workspace), making the
    // tasks read as "disabled".
  }
}

type Node = TaskNode | TaskFileGroupNode | TaskFileNode | PrefToggleNode | TaskSourceGroupNode;

function iconForType(type: TaskConfig['type']): vscode.ThemeIcon {
  switch (type) {
    case 'command': return new vscode.ThemeIcon('terminal');
    case 'upload': return new vscode.ThemeIcon('cloud-upload');
    case 'script': return new vscode.ThemeIcon('file-code');
  }
}

/** MIME type used by the Tasks tree DnD handshake. Convention is
 *  `application/vnd.code.tree.<viewId>` — VSCode requires both source and
 *  destination to declare the same string for drag-and-drop to fire. */
const TASK_TREE_MIME = 'application/vnd.code.tree.ssh-fleet.tasks';

export class TaskTreeProvider
  implements vscode.TreeDataProvider<Node>, vscode.TreeDragAndDropController<Node>, vscode.Disposable
{
  private readonly emitter = new vscode.EventEmitter<void>();
  readonly onDidChangeTreeData = this.emitter.event;

  // DnD handshake. We accept and produce only our own MIME type — copying
  // tasks out to the OS file manager / external apps doesn't make sense.
  readonly dragMimeTypes = [TASK_TREE_MIME];
  readonly dropMimeTypes = [TASK_TREE_MIME];

  private config: AppConfig;
  private readonly subs: vscode.Disposable[] = [];
  /** Cached list of `*.yml` files in `<workspace>/tasks/`. */
  private taskFiles: string[] = [];

  constructor(
    initial: AppConfig,
    onDidConfigChange: vscode.Event<AppConfig>,
    private readonly selection: SelectionState,
    private readonly workspace: Workspace,
    private readonly prefs: PrefsStore,
    private readonly configStore: ConfigStore
  ) {
    this.config = initial;
    this.subs.push(onDidConfigChange(c => {
      this.config = c;
      this.emitter.fire();
    }));
    this.subs.push(selection.onDidChange(() => this.emitter.fire()));
    this.subs.push(prefs.onDidChange(() => this.emitter.fire()));
    // Watch the tasks dir so the inline file list refreshes when files
    // appear or disappear without requiring a config reload.
    const dir = workspace.tasksDir();
    if (dir) {
      const watcher = vscode.workspace.createFileSystemWatcher(
        new vscode.RelativePattern(dir, '*.{yml,yaml}')
      );
      watcher.onDidCreate(() => this.refreshTaskFiles());
      watcher.onDidDelete(() => this.refreshTaskFiles());
      this.subs.push(watcher);
    }
    void this.refreshTaskFiles();
  }

  private async refreshTaskFiles(): Promise<void> {
    const dir = this.workspace.tasksDir();
    if (!dir) {
      this.taskFiles = [];
      this.emitter.fire();
      return;
    }
    try {
      const entries = await fs.readdir(dir);
      this.taskFiles = entries.filter(n => /\.ya?ml$/i.test(n)).sort();
    } catch {
      this.taskFiles = [];
    }
    this.emitter.fire();
  }

  bindCheckbox(treeView: vscode.TreeView<Node>): vscode.Disposable {
    return treeView.onDidChangeCheckboxState(ev => {
      for (const [item, newState] of ev.items) {
        const checked = newState === vscode.TreeItemCheckboxState.Checked;
        if (item.kind === 'task') {
          this.selection.setTask(item.task.name, checked);
        } else if (item.kind === 'task-file') {
          // Toggling a task-file checkbox flips it in/out of the persisted
          // `selectedTaskFiles` set; ConfigStore reload re-applies the
          // change and the Tasks list refreshes accordingly. The active-
          // config row is special: it routes through its own pref so we
          // can flip it without polluting the basename-keyed set.
          if (item.contextValue === 'task-file-active-config') {
            void this.prefs.setIncludeActiveConfigTasks(checked);
          } else {
            const cur = new Set(this.prefs.selectedTaskFiles);
            if (checked) cur.add(item.fileName); else cur.delete(item.fileName);
            void this.prefs.setSelectedTaskFiles([...cur]);
          }
        } else if (item.kind === 'pref-toggle' && item.prefId === 'deselectAfterRun') {
          void this.prefs.setDeselectAfterRun(checked);
        }
      }
    });
  }

  getTreeItem(node: Node): vscode.TreeItem {
    return node;
  }

  getChildren(element?: Node): Node[] {
    if (!element) {
      const out: Node[] = [];

      // Pref row at the very top — VSCode-native checkbox is the only
      // widget that renders a clear ticked / unticked state in extension
      // UI, so this lives where it's discoverable instead of being buried
      // in an overflow menu where codicons render inconsistently.
      out.push(new PrefToggleNode(
        'deselectAfterRun',
        'Untick task after run',
        this.prefs.deselectAfterRun
      ));

      // Task Files header — counts include the active config when its
      // tasks are loaded, so the badge matches what's actually in the tree.
      const filesActive = this.prefs.selectedTaskFiles.length
        + (this.prefs.includeActiveConfigTasks && this.activeConfigBasename() ? 1 : 0);
      const filesTotal = this.taskFiles.length + (this.activeConfigBasename() ? 1 : 0);
      out.push(new TaskFileGroupNode(filesActive, filesTotal));

      // Bucket tasks by their source file; a task with no recorded source
      // (e.g. legacy load before sources existed) falls under "(unknown)".
      const sources = this.configStore.taskSources;
      const buckets = new Map<string, TaskConfig[]>();
      for (const t of this.config.tasks) {
        const src = sources[t.name] ?? '(unknown)';
        const list = buckets.get(src) ?? [];
        list.push(t);
        buckets.set(src, list);
      }
      const ordered = [...buckets.entries()].sort(([a], [b]) => a.localeCompare(b));
      for (const [src, list] of ordered) {
        const label = src === '(unknown)' ? '(unknown)' : path.basename(src);
        out.push(new TaskSourceGroupNode(label, src, list.length));
      }
      return out;
    }
    if (element.kind === 'task-file-group') {
      const out: TaskFileNode[] = [];
      // Active config is surfaced first so the operator can untick it like
      // any other source. Routing goes to `includeActiveConfigTasks`.
      const cfgName = this.activeConfigBasename();
      const cfgPath = this.configStore.sources[0];
      if (cfgName) {
        out.push(new TaskFileNode(cfgName, this.prefs.includeActiveConfigTasks, {
          isActiveConfig: true,
          ...(cfgPath ? { fullPath: cfgPath } : {})
        }));
      }
      if (this.taskFiles.length > 0) {
        const sel = new Set(this.prefs.selectedTaskFiles);
        const tasksDir = this.workspace.tasksDir();
        for (const name of this.taskFiles) {
          out.push(new TaskFileNode(name, sel.has(name), {
            ...(tasksDir ? { fullPath: path.join(tasksDir, name) } : {})
          }));
        }
      }
      return out;
    }
    if (element.kind === 'task-source') {
      const sources = this.configStore.taskSources;
      return this.config.tasks
        .filter(t => (sources[t.name] ?? '(unknown)') === element.sourcePath)
        .map(t => new TaskNode(t, this.selection.isTaskSelected(t.name), element.sourcePath));
    }
    return [];
  }

  /** Read the active config basename from configStore.sources (first entry
   *  is the active config when one is loaded). */
  private activeConfigBasename(): string | undefined {
    const first = this.configStore.sources[0];
    return first ? path.basename(first) : undefined;
  }

  // ── Drag & drop ─────────────────────────────────────────────────────
  // Reorder is restricted to within a single source file. Cross-file drops
  // are rejected with a notification — moving a task between files would
  // need to also rewrite the destination's array (and decide whether to
  // copy or remove from source), which the operator can do faster by
  // editing the YAML directly.

  handleDrag(source: Node[], data: vscode.DataTransfer): void {
    const tasks = source.filter((n): n is TaskNode => n.kind === 'task');
    if (tasks.length === 0) return;
    const sources = this.configStore.taskSources;
    const sourcePaths = new Set(tasks.map(t => sources[t.task.name] ?? '(unknown)'));
    // All-from-one-file is the only valid drag — early-rejecting cross-file
    // drags here means the drop handler doesn't need to revalidate.
    if (sourcePaths.size !== 1) return;
    const sourcePath = [...sourcePaths][0];
    if (sourcePath === '(unknown)') return;
    // Carry full identities (not just names) so the drop side can match
    // YAML items even when the in-memory name is auto-generated for a
    // nameless YAML entry like `- command: hostname`.
    data.set(TASK_TREE_MIME, new vscode.DataTransferItem({
      sourcePath,
      moving: tasks.map(t => taskIdentity(t.task))
    }));
  }

  async handleDrop(target: Node | undefined, data: vscode.DataTransfer): Promise<void> {
    const item = data.get(TASK_TREE_MIME);
    if (!item) return;
    const payload = item.value as { sourcePath: string; moving: TaskIdentity[] } | undefined;
    if (!payload || !payload.sourcePath || !Array.isArray(payload.moving)) return;

    // Drop semantics. VSCode's tree DnD resolves the drop target by the
    // row visually under the cursor, with no "before/after gap" hints —
    // so "drop in the gap above the first task" can land us on a
    // TaskFileNode, a TaskFileGroupNode, the PrefToggleNode, the source-
    // group header, or the first task itself depending on pixels and
    // platform. Be lenient: anything that isn't a task in the same file
    // falls back to "top of the dragged source", which matches the most
    // common operator intent in those vague drop zones.
    //
    //   - on a task in same file → insert before/after by drag direction
    //   - on a task in OTHER file → reject with notification
    //   - on the source header   → prepend
    //   - empty area (undefined) → append
    //   - any other row          → fall back to prepend (best guess)
    let placement: DropPlacement;
    if (target?.kind === 'task') {
      const targetSrc = this.configStore.taskSources[target.task.name] ?? '(unknown)';
      if (targetSrc !== payload.sourcePath) {
        void vscode.window.showInformationMessage(
          `SSH Fleet: tasks can only be reordered within their own file (${path.basename(payload.sourcePath)}).`
        );
        return;
      }
      placement = { mode: 'before-task', target: taskIdentity(target.task) };
    } else if (target?.kind === 'task-source') {
      if (target.sourcePath !== payload.sourcePath) {
        void vscode.window.showInformationMessage(
          `SSH Fleet: tasks can only be reordered within their own file (${path.basename(payload.sourcePath)}).`
        );
        return;
      }
      placement = { mode: 'top' };
    } else if (target === undefined) {
      placement = { mode: 'bottom' };
    } else {
      // Any other tree row (Task Files children, prefs, etc.) — operator
      // is clearly not aiming at a specific task. Default to prepend.
      placement = { mode: 'top' };
    }

    await reorderTasksWithinSource(
      this.configStore,
      payload.sourcePath,
      payload.moving,
      placement
    );
  }

  refresh(): void {
    this.emitter.fire();
  }

  dispose(): void {
    for (const s of this.subs) {
      s.dispose();
    }
    this.emitter.dispose();
  }
}
